import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AppToaster } from "@/components/app-toaster";

const montserrat = Montserrat({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        style={{ fontFamily: montserrat.style.fontFamily }}
      >
        {children}

        <AppToaster />
      </body>
    </html>
  );
}
